spring.application.name=micro-services-oracle-cloud
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.from=${MAIL_FROM}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.email.sa-saopaulo-1.oci.oraclecloud.com
spring.mail.host=smtp.email.sa-saopaulo-1.oci.oraclecloud.com
spring.mail.port=587
spring.mail.protocol=smtp
